### ISSUE TITLE
FATAL ERROR: JS Allocation failed - process out of memory

### ISSUE THREAD

**Issue by borys** [andris9/buildmail#3]
Hello,
execution of following code ends with 'out of memory' error:

```javascript
var BuildMail = require('buildmail');

var builder = new BuildMail('text/html');
builder.setContent(new Buffer('http-equiv="Content-Type" content="text/html; charset=ISO-8859-2"\r\ntml\r'));

var stream = builder.createReadStream();
stream.pipe(process.stdout);
```
(it is minimal string, I've extracted from html page, that caused an error,  'http-eguiv[...]' is from `<meta>` tag, and 'tml' is from `<\html>` tag)

I've tested on two platforms:
* Linux, node version: v0.12.2, buildmail 1.2.1
* Windows 7, node version v0.10.29, buildmail 1.2.1

**Comment by andris9** [comment]
Fixed the issue (an eternal loop happened if the string ended with \r) and released as v1.2.2.
